TEST:
  FROM_TEMP: false
  SAVE_NAME: vortex_64_circular
  SETTING: vortex

MESH:
  GRID_SIZE: 100
  RESOLUTION: 0.64

GEOMS:
  FACET_ALGO: circular
  THRESHOLD: 1.0e-10
  DO_C0: false

ADVECTION:
  DT: 0.01
  T_TOTAL: 2