TEST:
  FROM_TEMP: false
  SAVE_NAME: ellipse_merge_noc0
  SETTING: ellipse_merge

MESH:
  GRID_SIZE: 100
  RESOLUTION: 1

GEOMS:
  FACET_ALGO: circular
  THRESHOLD: 1.0e-10
  DO_C0: false

ADVECTION:
  DO_ADVECT: false