TEST:
  FROM_TEMP: false
  SAVE_NAME: vortex_32
  SETTING: vortex

MESH:
  GRID_SIZE: 100
  RESOLUTION: 0.32

GEOMS:
  FACET_ALGO: circular
  THRESHOLD: 1.0e-10

ADVECTION:
  DT: 0.01
  T_TOTAL: 4