TEST:
  FROM_TEMP: false
  SAVE_NAME: vortex_128
  SETTING: vortex

MESH:
  GRID_SIZE: 100
  RESOLUTION: 1.28

GEOMS:
  FACET_ALGO: circular
  THRESHOLD: 1.0e-10

ADVECTION:
  DT: 0.01
  T_TOTAL: 2