TEST:
  FROM_TEMP: false
  SAVE_NAME: vortex_128_circular
  SETTING: vortex

MESH:
  GRID_SIZE: 100
  RESOLUTION: 1.28

GEOMS:
  FACET_ALGO: circular # Youngs, LVIRA, linear, circular, linear+corner, circular+corner
  THRESHOLD: 1.0e-10
  DO_C0: false

ADVECTION:
  DT: 0.01
  T_TOTAL: 2