TEST:
  FROM_TEMP: false
  SAVE_NAME: x+o_64_l+c
  SETTING: xpluso

MESH:
  GRID_SIZE: 100
  RESOLUTION: 1.00

GEOMS:
  FACET_ALGO: linear+corner
  THRESHOLD: 1.0e-10

ADVECTION:
  DT: 0.01
  T_TOTAL: 2