TEST:
  FROM_TEMP: false
  SAVE_NAME: x+o_32
  SETTING: xpluso

MESH:
  GRID_SIZE: 100
  RESOLUTION: 0.32

GEOMS:
  FACET_ALGO: linear
  THRESHOLD: 1.0e-10

ADVECTION:
  DT: 0.01
  T_TOTAL: 2