TEST:
  FROM_TEMP: false
  SAVE_NAME: line_lvira
  SETTING: line

MESH:
  GRID_SIZE: 100
  RESOLUTION: 0.5

GEOMS:
  FACET_ALGO: LVIRA
  THRESHOLD: 1.0e-10
  DO_C0: false

ADVECTION:
  DO_ADVECT: false