TEST:
  FROM_TEMP: false
  SAVE_NAME: x+o_50_safelinearcorner
  SETTING: xpluso

MESH:
  GRID_SIZE: 100
  RESOLUTION: 0.50

GEOMS:
  FACET_ALGO: safe_linear_corner
  THRESHOLD: 1.0e-10
  DO_C0: false

ADVECTION:
  DO_ADVECT: true
  DT: 0.01
  T_TOTAL: 2