TEST:
  FROM_TEMP: false
  SAVE_NAME: zalesak_50_lvira
  SETTING: zalesak

MESH:
  GRID_SIZE: 100
  RESOLUTION: 0.50

GEOMS:
  FACET_ALGO: LVIRA
  THRESHOLD: 1.0e-10
  DO_C0: false

ADVECTION:
  DO_ADVECT: true
  DT: 0.01
  T_TOTAL: 2